### PR TITLE
TNO-2215 Audio video layout fix

### PR DESCRIPTION
**Pull request by fbarreta**
image
Before

image
After

### CODE REVIEW

**Comment by jdtoombs** [comment]
Looks good! Just one small thing, I noticed after the changes the Publish/Save without publish button is no longer appearing in one row as shown in your attached images:

image

**Comment by kylgarmor** [comment]
hey Felipe.  Could you maybe change the percentage of the screen that the media section gets?  I dont see any reason for it to get 50% whereas the text-area could definitely benefit from more space

**Comment by fbarreta** [comment]
> Looks good! Just one small thing, I noticed after the changes the Publish/Save without publish button is no longer appearing in one row as shown in your attached images:
> 
> image

It's because my window size, the default behaviour when the size is smaller, when it's regular size, it looks the same:
image

**Comment by fbarreta** [comment]
> hey Felipe. Could you maybe change the percentage of the screen that the media section gets? I dont see any reason for it to get 50% whereas the text-area could definitely benefit from more space

Yeah ... looked better with 65%.
image

**Review by kylgarmor — APPROVED** [review]

**Pull request merged**
