### PR TITLE
TNO-854: Bold tabs

### PR DESCRIPTION
**Pull request by jdtoombs**
Quick PR to bold the label text within our Tab component

### CODE REVIEW

**Review by Fosol — APPROVED** [review]
The downside to minor updates to a shared library lol.  I wonder if we could come up with a way to reduce this if we had way more time to do everything?

**Comment by Fosol** [comment]
@jdtoombs Looks like you didn't do a proper merge and `yarn install`.  You'll need to resolve this, and also you'll need to update the subscriber package.json to use the new version of the `tno-core` library.

**Comment by jdtoombs** [comment]
@Fosol - forgot to pull down latest before my changes :( fixing now

**Comment by jdtoombs** [comment]
> The downside to minor updates to a shared library lol. I wonder if we could come up with a way to reduce this if we had way more time to do everything?

Lol yes, that would be ideal. Could do some brainstorming!

**Comment by jdtoombs** [comment]
Screwed up the branch

**Pull request closed without merging**
