### PR TITLE
TNO-2770 Add do not send email property

### PR DESCRIPTION
**Pull request by fbarreta**
Added DoNotSendEmail property to report settings.

Published tno-core:0.1.94

### CODE REVIEW

**Review by Fosol — COMMENTED** [review]
You appear to be missing the logic that would stop the report from being emailed in the ReportingService.

**Comment by Fosol** [comment]
Ah in the next PR!  Do you want to keep these together?

**Comment by fbarreta** [comment]
> Ah in the next PR! Do you want to keep these together?

Yes we can, whatever it's easier.

**Comment by Fosol** [comment]
We'll have to wait for Jonny's PR as it has a blocking tno-core version.

**Comment by fbarreta** [comment]
> We'll have to wait for Jonny's PR as it has a blocking tno-core version.

Just merged the other PR, so once you can publish a new tno-core version. I would ask you please to update and then merge my PR.

**Review by Fosol — APPROVED** [review]

**Pull request merged**
