### PR TITLE
Merge content migration services into one

### PR DESCRIPTION
**Pull request by laidaoyu**
- removed content-migration historic image, AV, online, and print services
- created content-migration historic service, this service should handle image, AV, online and print contents

### CODE REVIEW

**Review by Fosol — COMMENTED** [review]
Looks good.

I think you should also include an update to the Tekton deploy-all task `/openshift/kustomize/tekton/base/tasks/deploy.all.yaml`

**Comment by laidaoyu** [comment]
> deploy.all.yaml

I don't see the code needs to be changed in deploy-all.yaml file

**Comment by Fosol** [comment]
I think I was looking at an old copy.  Looks like you've updated it to `content-historic-service` already.

**Comment by laidaoyu** [comment]
> I think I was looking at an old copy. Looks like you've updated it to `content-historic-service` already.

Thank you!

**Pull request merged**
